#
# Makefile for the NTS device drivers.
#

obj-$(CONFIG_X223WO_FPGA_CONFIG)	+= fpga_config.o
obj-$(CONFIG_X223WO_IF_FPGA)	+= if_fpga.o
obj-$(CONFIG_X223WO_LED)		+= led.o
obj-$(CONFIG_X223WO_WATCHDOG)		+= watchdog.o
obj-$(CONFIG_X223WO_POWER)		+= power.o
obj-$(CONFIG_X223WO_RESET)		+= reset.o
obj-$(CONFIG_X223WO_RTC)		+= rtc.o
obj-$(CONFIG_X223WO_ADC)		+= adc.o
obj-$(CONFIG_X223WO_STATUS)		+= status.o
obj-$(CONFIG_X223WO_DAC)		+= dac.o
obj-$(CONFIG_X223WO_VERSION)		+= version.o
obj-$(CONFIG_X223WO_LMK04031)		+= lmk04031.o
obj-$(CONFIG_X223WO_ADF4350)		+= adf4350.o
obj-$(CONFIG_X223WO_TMP125)		+= tmp125.o

