header-n += errno-base.h
header-n += errno.h
header-n += fcntl.h
header-n += ioctl.h
header-n += mman.h
header-n += poll.h
header-n += signal.h
header-n += statfs.h

unifdef-n += int-l64.h
unifdef-n += int-ll64.h
unifdef-n += resource.h
unifdef-n += siginfo.h
