#
# Makefile for the NTS device drivers.
#

obj-$(CONFIG_G200WO_FPGA_CONFIG)	+= fpga_config.o
obj-$(CONFIG_G200WO_GSM)		+= gsm.o
obj-$(CONFIG_G200WO_LED)		+= led.o
obj-$(CONFIG_G200WO_WATCHDOG)		+= watchdog.o
obj-$(CONFIG_G200WO_POWER)		+= power.o
obj-$(CONFIG_G200WO_RESET)		+= reset.o
obj-$(CONFIG_G200WO_RTC)		+= rtc.o
obj-$(CONFIG_G200WO_ADC)		+= adc.o
obj-$(CONFIG_G200WO_STATUS)		+= status.o
obj-$(CONFIG_G200WO_TX_DAC)		+= tx_dac.o
obj-$(CONFIG_G200WO_VERSION)		+= version.o
obj-$(CONFIG_G200WO_LMK03000)		+= lmk03000.o
obj-$(CONFIG_G200WO_ADF4350)		+= adf4350.o
obj-$(CONFIG_G200WO_TMP125)		+= tmp125.o

