#
# Makefile for the NTS device drivers.
#

obj-$(CONFIG_G410SD_FPGA_CONFIG)	+= fpga_config.o
obj-$(CONFIG_G410SD_IF_FPGA)		+= if_fpga.o
obj-$(CONFIG_G410SD_GSM)		+= gsm.o
obj-$(CONFIG_G410SD_LED)		+= led.o
obj-$(CONFIG_G410SD_WATCHDOG)		+= watchdog.o
obj-$(CONFIG_G410SD_POWER)		+= power.o
obj-$(CONFIG_G410SD_RESET)		+= reset.o
obj-$(CONFIG_G410SD_RTC)		+= rtc.o
obj-$(CONFIG_G410SD_ADC)		+= adc.o
obj-$(CONFIG_G410SD_STATUS)		+= status.o
obj-$(CONFIG_G410SD_DAC)		+= dac.o
obj-$(CONFIG_G410SD_VERSION)		+= version.o
obj-$(CONFIG_G410SD_LMK03000)		+= lmk03000.o
obj-$(CONFIG_G410SD_LMK2531)		+= lmk2531.o
obj-$(CONFIG_G410SD_TMP125)		+= tmp125.o
obj-$(CONFIG_G410SD_SFP)		+= sfp.o
obj-$(CONFIG_G410SD_CPRI)		+= cpri_eth.o

