# Top-level Makefile calls into asm-$(ARCH)
# List only non-arch directories below

header-n += asm-generic/
header-n += linux/
header-n += sound/
header-n += mtd/
header-n += rdma/
header-n += video/
header-n += drm/
header-y += g200wo/
header-y += g410sd/
