#
# Makefile for the NTS device drivers.
#

obj-$(CONFIG_NTS_FPGA_CONFIG)	+= fpga_config.o
obj-$(CONFIG_NTS_IF_FPGA)	+= if_fpga.o
obj-$(CONFIG_NTS_LED)		+= led.o
obj-$(CONFIG_NTS_WATCHDOG)	+= watchdog.o
obj-$(CONFIG_NTS_RESET)		+= reset.o
obj-$(CONFIG_NTS_RTC)		+= rtc.o
obj-$(CONFIG_NTS_ADC)		+= adc.o
obj-$(CONFIG_NTS_ADC_28V)	+= adc_28v.o
obj-$(CONFIG_NTS_STATUS)	+= status.o
obj-$(CONFIG_NTS_DAC)		+= dac.o
obj-$(CONFIG_NTS_VERSION)	+= version.o
obj-$(CONFIG_NTS_LMK04031)	+= lmk04031.o
obj-$(CONFIG_NTS_ADF4350)	+= adf4350.o
obj-$(CONFIG_NTS_TMP125)	+= tmp125.o

