#
# Makefile for the NTS device drivers.
#

obj-$(CONFIG_G420SD_FPGA_CONFIG)   += fpga_config.o
obj-$(CONFIG_G420SD_IF_FPGA)       += if_fpga.o
obj-$(CONFIG_G420SD_FPGA_RAM)      += fpga_ram.o
obj-$(CONFIG_G420SD_LED)	   += led.o
obj-$(CONFIG_G420SD_WATCHDOG)	   += watchdog.o
obj-$(CONFIG_G420SD_ADC28V)	   += adc_28v.o
obj-$(CONFIG_G420SD_RESET)	   += reset.o
obj-$(CONFIG_G420SD_RTC)	   += rtc.o
obj-$(CONFIG_G420SD_ADC)	   += adc.o
obj-$(CONFIG_G420SD_STATUS)	   += status.o
obj-$(CONFIG_G420SD_DAC)	   += dac.o
obj-$(CONFIG_G420SD_VERSION)	   += version.o
obj-$(CONFIG_G420SD_LMK04031)	   += lmk04031.o
obj-$(CONFIG_G420SD_ADF4350)	   += adf4350.o
obj-$(CONFIG_G420SD_TMP125)	   += tmp125.o
obj-$(CONFIG_G420SD_RS422_BYTE_TIME)   += rs422_byte_time.o



