#
# Makefile for the NTS device drivers.
#

obj-$(CONFIG_X223FT_FPGA_CONFIG)	+= fpga_config.o
obj-$(CONFIG_X223FT_FPGA_RAM)	+= fpga_ram.o
obj-$(CONFIG_X223FT_IF_FPGA)	+= if_fpga.o
obj-$(CONFIG_X223FT_LED)		+= led.o
obj-$(CONFIG_X223FT_WATCHDOG)		+= watchdog.o
obj-$(CONFIG_X223FT_RESET)		+= reset.o
obj-$(CONFIG_X223FT_RTC)		+= rtc.o
obj-$(CONFIG_X223FT_ADC)		+= adc.o
obj-$(CONFIG_X223FT_STATUS)		+= status.o
obj-$(CONFIG_X223FT_DAC)		+= dac.o
obj-$(CONFIG_X223FT_VERSION)		+= version.o
obj-$(CONFIG_X223FT_LMK04031)		+= lmk04031.o
obj-$(CONFIG_X223FT_ADF4350)		+= adf4350.o
obj-$(CONFIG_X223FT_TMP125)		+= tmp125.o
obj-$(CONFIG_X223FT_CPRI)		+= cpri_eth.o

